/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PascualBravo.CleanCar;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Johan Arboleda
 */
public class vista1 extends javax.swing.JFrame {

    /**
     * Creates new form vista1
     */
    public vista1() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imgLogo = new ImageIcon("src\\main\\java\\Recursos\\logo.png");
        lblLogo.setIcon(new ImageIcon(imgLogo.getImage().getScaledInstance(lblLogo.getWidth(),lblLogo.getHeight(), Image.SCALE_SMOOTH)));
        
        ImageIcon imgCar = new ImageIcon("src\\main\\java\\Recursos\\Imagen1.png");
        lblCarro.setIcon(new ImageIcon(imgCar.getImage().getScaledInstance(120, 90, Image.SCALE_SMOOTH)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnEmpezarDia = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnFinalizarDia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCarro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNombreadmin4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblNombreadmin1 = new javax.swing.JLabel();
        lblNombreadmin3 = new javax.swing.JLabel();
        lblNombreadmin2 = new javax.swing.JLabel();
        lblnominDia = new javax.swing.JLabel();
        lblnominDia1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 102, 102));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 246, 251));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 680));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpezarDia.setBackground(new java.awt.Color(0, 153, 204));
        btnEmpezarDia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnEmpezarDia.setForeground(new java.awt.Color(0, 0, 0));
        btnEmpezarDia.setText("Empezar día");
        btnEmpezarDia.setBorder(null);
        jPanel1.add(btnEmpezarDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 270, 40));

        btnServicios.setBackground(new java.awt.Color(0, 153, 204));
        btnServicios.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(0, 0, 0));
        btnServicios.setText("Servicio");
        btnServicios.setBorder(null);
        jPanel1.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 260, 80));

        btnFinalizarDia.setBackground(new java.awt.Color(0, 153, 204));
        btnFinalizarDia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        btnFinalizarDia.setForeground(new java.awt.Color(0, 0, 0));
        btnFinalizarDia.setText("Finalizar día");
        btnFinalizarDia.setBorder(null);
        jPanel1.add(btnFinalizarDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 510, 270, 40));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(246, 246, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 140, 50));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Juan Carlos Meza", "50.000", "2", "disponible", null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre Trabajador", "Producido", "Carros lavados", "Estado", "Eliminar"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(800, 500));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Nombre Trabajador");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Producido");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Carros lavados");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Estado");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Eliminar");
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 310));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 920, 330));

        lblNombreadmin4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblNombreadmin4.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreadmin4.setText("Nombre del administrador");
        jPanel1.add(lblNombreadmin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 300, 60));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(246, 246, 251));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreadmin1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblNombreadmin1.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreadmin1.setText("Hora:");
        jPanel4.add(lblNombreadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 30));

        lblNombreadmin3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblNombreadmin3.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreadmin3.setText("00:00:00");
        jPanel4.add(lblNombreadmin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 110, 30));

        lblNombreadmin2.setBackground(new java.awt.Color(153, 153, 153));
        lblNombreadmin2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        lblNombreadmin2.setForeground(new java.awt.Color(51, 51, 51));
        lblNombreadmin2.setText("Nominda del día:");
        jPanel4.add(lblNombreadmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 50));

        lblnominDia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 50)); // NOI18N
        lblnominDia.setForeground(new java.awt.Color(0, 0, 0));
        lblnominDia.setText("$");
        jPanel4.add(lblnominDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 70));

        lblnominDia1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 50)); // NOI18N
        lblnominDia1.setForeground(new java.awt.Color(0, 0, 0));
        lblnominDia1.setText("250.000");
        jPanel4.add(lblnominDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 220, 70));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 590, 120));

        lblLogo.setForeground(new java.awt.Color(0, 0, 0));
        lblLogo.setText("LOGO");
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 120));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new vista1().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezarDia;
    private javax.swing.JButton btnFinalizarDia;
    private javax.swing.JButton btnServicios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreadmin1;
    private javax.swing.JLabel lblNombreadmin2;
    private javax.swing.JLabel lblNombreadmin3;
    private javax.swing.JLabel lblNombreadmin4;
    private javax.swing.JLabel lblnominDia;
    private javax.swing.JLabel lblnominDia1;
    // End of variables declaration//GEN-END:variables
}
